### ISSUE TITLE
Make CV array container do smarter things

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#379]
* property for velocity (others?)
* deprecate `get_num_species`, replace with better
* memoize on CV for expensive derived quantities

**Comment by majosm** [comment]
I haven't been following the array container changes very closely... do we still use CV as a general container for anything corresponding to the fluid equations? i.e., more than just the state?

If so, I wonder if it might be confusing to add derived quantity methods directly to CV (because, for example, I don't know if a `temperature()` method really makes sense when CV is storing fluxes). Maybe it would be better to create a fluid state class that contains a CV and also defines these derived quantity methods?

**Comment by MTCam** [comment]
> I haven't been following the array container changes very closely... do we still use CV as a general container for anything corresponding to the fluid equations? i.e., more than just the state?

CV is used the same as before, to store scalar or vector quantities for each fluid conservation equation.  

> 
> If so, I wonder if it might be confusing to add derived quantity methods directly to CV (because, for example, I don't know if a `temperature()` method really makes sense when CV is storing fluxes). Maybe it would be better to create a fluid state class that contains a CV and also defines these derived quantity methods?

I hadn't planned on adding methods per-se to CV. The velocity thing:

```python
@memoize blah blah
@property
def velocity(self):
  return self.momentum / self.mass
```

.. just for convenience, because we use this *a lot* - and to me it makes sense to add this as a property to CV.  For expensive DV, like temperature, pressure, etc, I had only planned on memoizing on CV, not containing or calling a method inside the CV.
