### ISSUE TITLE
Axisymmetric?

### ISSUE THREAD

**Issue by majosm** [illinois-ceesd/mirgecom#504]
It looks like our current target for an initial fluid-wall coupling simulation is axisymmetric. Do we have an axisymmetric capability in the MIRGE stack right now? If not, what would be involved in adding one? Do the governing equations need to be modified? Or can this be done by changing how the integrals are evaluated?

I guess an alternate way to do this might be to make it rotationally-periodic instead. But we would need some development yet to make that work (specifically: transforming the fluxes at the periodic boundary).

cc @inducer, @jbfreund

**Comment by jbfreund** [comment]
Good point, Matt.  Ideally we would add this capability.  Hopefully it would not be too hard.  The coarse in theta approach should also be fine.  This warrants discussion.

**Comment by inducer** [comment]
> If not, what would be involved in adding one?

This paper (EM rather than fluids, but still) might give you a sense: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=753003

I'm not sure it's worth it vs the other approaches. You pick up extra metric terms (fine, if potentially error-prone) and you need to bend over backwards a bit to deal with the (artificial) singularity at the origin.

**Comment by inducer** [comment]
Found another paper that does axisymmetric DG for fluids: https://doi.org/10.1007/978-3-642-59721-3_27
