### ISSUE TITLE
Compile hangs for 3D prediction w/ full physics

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/mirgecom#783]
This issue is effectively preventing 3D prediction cases. It happens for certain parallel decompositions in lazy mode (eager works fine), and is indicative of a parallel processing bug in MIRGE-Com.  To reproduce:

1. install mirgecom@production
2. grab git@github.com:/illinois-ceesd/drivers_y2-prediction@profiling-version
3. Run `smoke_test_ks` on 16 MPI ranks

e.g., `jsrun -g 1 -a 1 -n 16 python -u -m mpi4py ./prediction.py -i run_params.yaml --lazy'`

> Note: the `profiling-version` branch of the y2-prediction driver is set up to run a 3D case on Lassen. `drivers_y2-prediction@main` will reproduce this problem, but the case will need hand-tweaking to run 3D, and will require a 3D grid (which are pre-built on Lassen).

Eventually, the compile will hang... like this:
```
(...)
2022-10-18 05:45:25,603 - INFO - meshmode.array_context - Transforming kernel with 13 statements.
2022-10-18 05:45:25,825 - INFO - meshmode.array_context - Array Contraction: Contracting 0 temps
2022-10-18 05:45:25,840 - INFO - meshmode.array_context - [_alias_global_temporaries]: Reduced memory requirement from 0.0MB to 0.0MB.
2022-10-18 05:45:26,718 - INFO - pyopencl - build program: kernel 'frozen_result' was part of a lengthy source build resulting from a binary cache miss (0.40 s)
2022-10-18 05:45:29,102 - INFO - pyopencl - build program: kernel 'my_rhs' was part of a lengthy source build resulting from a binary cache miss (12.93 s)
2022-10-18 05:45:31,676 - INFO - pyopencl - build program: kernel 'my_rhs' was part of a lengthy source build resulting from a binary cache miss (13.25 s)
```

Attaching a debugger to one of the running compile processes says they are all very busy doing this:
```
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/mirgecom/mirgecom/integrators/lsrk.py", line 66, in euler_step
    return lsrk_step(EulerCoefs, state, t, dt, rhs)
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/mirgecom/mirgecom/integrators/lsrk.py", line 53, in lsrk_step
    k = coefs.A[i]*k + dt*rhs(t + coefs.C[i]*dt, state)
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/arraycontext/arraycontext/impl/pytato/compile.py", line 372, in __call__
    return compiled_func(arg_id_to_arg)
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/grudge/grudge/array_context.py", line 363, in __call__
    out_dict = execute_distributed_partition(
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/pytato/pytato/distributed.py", line 1231, in execute_distributed_partition
    wait_for_some_recvs()
  File "/p/gpfs1/mtcampbe/CEESD/Experimental/svm/production4/pytato/pytato/distributed.py", line 1195, in wait_for_some_recvs
    complete_recv_indices = MPI.Request.Waitsome(recv_requests)
```

Suspicions:
1. Promiscuous matching in collective communications (code hangs in collective in `logpyle` if logpyle is enabled, else global timestepping collectives when logpyle is disabled).  Both logpyle and timestep calculations are disabled in `profiling-version` branch.
2. Mismatching, missing, or colliding comm tags (So far, inspecting, adding, and tweaking tags has not been effective at fixing.  Several operators are called multiple times in a single RHS and should all get unique comm tags).
3. Some bug in mass loss model (disabling the mass loss RHS resolves the hang (but leaves incomplete physics))
4. Some bug in communication handling in grudge/meshmode - esp when multivol?

**Comment by inducer** [comment]
Given the discussion in #784, it would be useful to me to get a pickled version of the DAG reporting the cycle before (and, ideally, after) partitioning. There's a small gotcha to pickling the DAG because it contains device arrays in `DataWrapper`s. Converting those to plain numpy via, e.g. [`map_and_copy`](https://documen.tician.de/pytato/dag.html#pytato.transform.map_and_copy) should remove that gotcha.

**Comment by majosm** [comment]
@matthiasdiener The following commands should reproduce the current issue on Lassen:

```
git clone git@github.com:illinois-ceesd/drivers_y2-prediction.git y2-prediction
cd y2-prediction
git checkout debug-3d-hang
module load gcc/7.3.1
module load spectrum-mpi
./buildMirge.sh --use-ssh
export CONDA_PATH=<wherever conda was installed>
cd smoke_test_ks_3d
bsub runLassenBatch.sh
```
(Unfortunately I don't know of any simpler cases than the full prediction that trigger this. On the upside though it's just a single-node run.)

**Comment by majosm** [comment]
Some updates...

It looks like there is indeed a cycle in the distributed partition. It turns out that the node reported in the `CycleError` is not necessarily part of the cycle, but it does appear to be connected to it. Specifically, if I follow the first predecessor of each node starting from the reported one, I see something like this:

```
node=_DistributedPartId(rank=9, part_id=0)
node=_DistributedPartId(rank=10, part_id=1)
node=_DistributedPartId(rank=11, part_id=1)
node=_DistributedPartId(rank=12, part_id=1)
node=_DistributedPartId(rank=11, part_id=1)
```

(notice how it goes from the part on rank 11 to one on rank 12 and then back).

To attempt to narrow down which sends/recvs are causing the cycle between 11 and 12 I disabled some of the physics in order to get a run that doesn't hang (I turned off AV in this case), and then I diffed the partition output between the two runs to see what changed. Here are the diffs: [rank 11](https://gist.github.com/majosm/96de01151f89717aeaaf44992927e28b) and [rank 12](https://gist.github.com/majosm/64b460d31a3d1287f2673bfa5f8a874b). The full output for the hanging case is here: [rank 11](https://gist.github.com/majosm/29ce3f0d3abd6a78c9c565769cc0ca21) and [rank 12](https://gist.github.com/majosm/17285901bc8e7a76095906301683db06).

From what I can tell, the cycle seems to come from the `_KappaInterVolTag`. In both the hanging/non-hanging cases, the two parts receive `kappa` from each other. But, in the former case they are also responsible for sending it, hence the hang.

I'm not sure where to go from here as far as attempting to fix this. Does anyone have any suggestions? I'm not sure if it's an issue in the inter-volume exchange code or something in pytato (for reference, the code used for the inter-volume sends/recvs is [here](https://github.com/majosm/grudge/blob/3af1ca55d62fe1e7b187a63b6543ea35e3273e64/grudge/trace_pair.py#L700-L720)).

**Comment by majosm** [comment]
Here's a visualization of the partition graph: ![code](https://user-images.githubusercontent.com/7232918/202588019-9988359b-d0be-4e94-abc1-feb9f75a3f20.svg)

Zoomed in on the cycle:
![cycle](https://user-images.githubusercontent.com/7232918/202588178-90a682f2-3518-4e5e-acce-fc5abe495a7d.png)

**Comment by majosm** [comment]
> Given the discussion in #784, it would be useful to me to get a pickled version of the DAG reporting the cycle before (and, ideally, after) partitioning. There's a small gotcha to pickling the DAG because it contains device arrays in `DataWrapper`s. Converting those to plain numpy via, e.g. [`map_and_copy`](https://documen.tician.de/pytato/dag.html#pytato.transform.map_and_copy) should remove that gotcha.

With @matthiasdiener's help I got the DAGs pickled and written out, replacing the `DataWrapper`s with placeholders. One slight complication is that the files can only be read from the prediction driver (because they contain tags defined within the driver). I put the files and the code to read them in the `debug-3d-hang-pickled-dags` branch of the prediction driver repo. It requires some code from my debug branches of the subpackages; install procedure is the same as above.
